working_dir: &working_dir ~/app
version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 

jobs: 
  job:
    parallelism: 10
    docker: 
      - image: cimg/python:3.8 
     
    steps: 
      - checkout 
      - run: chmod +x ./install.sh
      - run: ./install.sh
workflows:
  version: 2
  commit:
    jobs:
      - job

    triggers:
      - schedule:
           cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master

  serverrunjob:
    jobs:
      - job
